import React, { useEffect, useState } from 'react';
import { Copy, Database, Play, Trash2 } from 'lucide-react';
import { sqlApi, type SqlResult } from '../api/sql';
import { AppPage, Card, PageHeader } from '../components/common';

const SqlConsolePage: React.FC = () => {
  const [tables, setTables] = useState<string[]>([]); const [sql, setSql] = useState('');
  const [result, setResult] = useState<SqlResult | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [copied, setCopied] = useState('');
  useEffect(() => { void sqlApi.getTables().then(setTables).catch((e) => setError(e?.message || '无法加载表列表')); }, []);
  const execute = async () => { if (!sql.trim()) return; setLoading(true); setError(''); try { setResult(await sqlApi.execute(sql)); void sqlApi.getTables().then(setTables); } catch (e: unknown) { const value = e as { message?: string; parsedError?: { message?: string } }; setError(value?.parsedError?.message || value?.message || 'SQL 执行失败'); } finally { setLoading(false); } };
  const copyTable = async (name: string) => { await navigator.clipboard?.writeText(`"${name.replaceAll('"', '""')}"`); setCopied(name); window.setTimeout(() => setCopied(''), 1200); };
  return <AppPage><PageHeader title="SQL 执行" description="直接查看和操作当前 SQLite 数据库。请谨慎执行写入或结构变更语句。" />
    <div className="mt-5 grid gap-5 lg:grid-cols-[240px_minmax(0,1fr)]"><Card className="h-fit p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><Database className="h-4 w-4" />数据库表</div>{tables.length ? tables.map((t) => <div key={t} className="flex items-center justify-between gap-2 border-b border-border/40 py-2 text-sm"><span className="truncate">{t}</span><button className="btn-ghost p-1" title="复制表名" onClick={() => void copyTable(t)}><Copy className="h-4 w-4" />{copied === t ? '✓' : ''}</button></div>) : <p className="text-sm text-secondary-text">暂无表</p>}</Card>
      <div className="space-y-5"><Card className="p-4"><textarea className="min-h-44 w-full rounded-xl border border-border bg-base p-3 font-mono text-sm text-foreground outline-none focus:border-primary" placeholder="输入 SQL，例如 SELECT * FROM stocks LIMIT 20" value={sql} onChange={(e) => setSql(e.target.value)} /><div className="mt-3 flex gap-2"><button className="btn-primary" disabled={loading || !sql.trim()} onClick={() => void execute()}><Play className="mr-1 h-4 w-4" />{loading ? '执行中...' : '执行'}</button><button className="btn-secondary" onClick={() => { setSql(''); setResult(null); setError(''); }}><Trash2 className="mr-1 h-4 w-4" />清空</button></div>{error && <p className="mt-3 text-sm text-red-500">{error}</p>}</Card>
        <Card className="overflow-hidden p-4"><div className="mb-3 font-semibold">执行结果</div>{result ? <>{result.affectedRows != null && <p className="mb-3 text-sm text-secondary-text">影响行数：{result.affectedRows}</p>}{result.columns.length ? <div className="max-h-[32rem] overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{result.columns.map((c) => <th key={c} className="whitespace-nowrap border-b border-border px-3 py-2">{c}</th>)}</tr></thead><tbody>{result.rows.map((row, i) => <tr key={i}>{row.map((v, j) => <td key={j} className="border-b border-border/40 px-3 py-2 align-top">{v == null ? 'NULL' : String(v)}</td>)}</tr>)}</tbody></table></div> : <p className="text-sm text-secondary-text">语句执行成功，无查询结果。</p>}{result.truncated && <p className="mt-3 text-xs text-amber-500">结果已截断，仅展示前 500 行。</p>}</> : <p className="text-sm text-secondary-text">执行 SQL 后将在此展示结果。</p>}</Card></div></div></AppPage>;
};
export default SqlConsolePage;
