/* eslint-disable react-hooks/set-state-in-effect, no-irregular-whitespace */
import { useEffect, useState } from 'react';
import { Button, Card, Input, Select, Switch, Table, Tabs, Tag } from 'antd';
import { liveStrategyApi, type LiveStrategyConfig, type LiveStrategyDefinition, type LiveStrategyPreview, type LiveStrategyRun, type LiveStrategyBatch, type LiveStrategySyncStatus, type LiveStrategyRunMode } from '../../api/liveStrategy';

const RUN_MODE_OPTIONS: Array<{ value: LiveStrategyRunMode; label: string }> = [
  { value: 'auto', label: '自动' },
  { value: 'rebalance', label: '调仓' },
  { value: 'event_check', label: '事件检查' },
];

export const LiveStrategyPanel: React.FC = () => {
  const [config,setConfig]=useState<LiveStrategyConfig>({strategyId:'low-premium',strategyVersion:'v1',qmtAccount:'testS',enabled:false,symbols:[],parameters:{}});
  const [defs,setDefs]=useState<LiveStrategyDefinition[]>([]); const [preview,setPreview]=useState<LiveStrategyPreview|null>(null); const [runs,setRuns]=useState<LiveStrategyRun[]>([]); const [batches,setBatches]=useState<LiveStrategyBatch[]>([]); const [sync,setSync]=useState<LiveStrategySyncStatus|null>(null); const [selected,setSelected]=useState<LiveStrategyRun|null>(null); const [details,setDetails]=useState<{decisions:unknown[];orders:unknown[]}>({decisions:[],orders:[]}); const [message,setMessage]=useState(''); const [runMode,setRunMode]=useState<LiveStrategyRunMode>('auto');
  const refresh=async()=>{const [c,d,r,b,s]=await Promise.all([liveStrategyApi.getConfig(),liveStrategyApi.listStrategies(),liveStrategyApi.listRuns(),liveStrategyApi.listBatches(),liveStrategyApi.syncStatus()]);setConfig(c);setDefs(d);setRuns(r);setBatches(b);setSync(s);}; useEffect(()=>{void refresh().catch(()=>undefined);},[]);
  const def=defs.find(d=>d.strategyId===config.strategyId); const act=async(fn:()=>Promise<unknown>,msg:string)=>{try{const x=await fn();if(x&&typeof x==='object'&&'rebalance' in x)setPreview(x as LiveStrategyPreview);if(msg==='配置已保存'&&x&&typeof x==='object'&&'strategyId' in x)setConfig(x as LiveStrategyConfig);setMessage(msg);if(msg!=='配置已保存')await refresh();}catch(e){setMessage(e instanceof Error?e.message:'操作失败');}}; const selectRun=async(r:LiveStrategyRun)=>{setSelected(r); const [decisions,orders]=await Promise.all([liveStrategyApi.listDecisions(r.id),liveStrategyApi.listOrders(r.id)]); setDetails({decisions,orders});};
  const syncItem=(x:LiveStrategySyncStatus['intraday'])=><span><Tag color={x?.status==='completed'?'green':x?.status==='failed'?'red':'orange'}>{x?.status||'未运行'}</Tag>{x?.completedAt&&<small>{new Date(x.completedAt).toLocaleTimeString()}</small>}{x?.errorMessage&&<small className="text-red-600">：{x.errorMessage}</small>}</span>;
  const configTab=<Card><div className="grid gap-3 sm:grid-cols-3"><Select value={config.qmtAccount} options={[{value:'testS',label:'testS'},{value:'135129739',label:'135129739'}]} onChange={qmtAccount=>setConfig({...config,qmtAccount})}/><Select value={config.strategyId} options={defs.map(d=>({value:d.strategyId,label:d.name}))} onChange={strategyId=>setConfig({...config,strategyId})}/><label>自动实盘 <Switch checked={config.enabled} onChange={enabled=>setConfig({...config,enabled})}/></label></div><p>{def?.description}</p><div className="grid gap-2 sm:grid-cols-4">{(def?.parameters||[]).map(p=><Input key={p.key} type="number" addonBefore={p.label} value={String(config.parameters[p.key]??p.default??'')} onChange={e=>setConfig({...config,parameters:{...config.parameters,[p.key]:Number(e.target.value)}})}/>)}</div><div className="mt-2 grid gap-2 sm:grid-cols-4"><Input type="number" addonBefore="调仓频率(交易日)" value={String(config.rebalanceFrequencyDays??1)} onChange={e=>setConfig({...config,rebalanceFrequencyDays:Math.max(1,Number(e.target.value)||1)})}/><Input addonBefore="自选池" placeholder="逗号分隔，留空=全市场" value={config.symbols.join(',')} onChange={e=>setConfig({...config,symbols:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/><label>下单前数据同步检查 <Switch checked={config.dataSyncBeforeRun??true} onChange={dataSyncBeforeRun=>setConfig({...config,dataSyncBeforeRun})}/></label></div><div className="mt-3 flex flex-wrap items-center gap-2"><Button onClick={()=>void act(()=>liveStrategyApi.saveConfig(config),'配置已保存')}>保存配置</Button><Select className="w-28" value={runMode} options={RUN_MODE_OPTIONS} onChange={m=>setRunMode(m as LiveStrategyRunMode)}/><Button onClick={()=>void act(()=>liveStrategyApi.preview(undefined,runMode),'预览已生成')}>预览</Button><Button type="primary" disabled={!config.enabled} onClick={()=>void act(()=>liveStrategyApi.run(undefined,runMode),'订单已生成')}>生成实盘订单</Button>{config.nextRebalanceDate&&<small>下次调仓：{config.nextRebalanceDate}</small>}{message&&<Tag>{message}</Tag>}</div></Card>;
  const previewTab=preview?<><Table rowKey={(r)=>`${r.side}-${r.symbol}`} dataSource={preview.rebalance} columns={[{title:'标的',dataIndex:'symbol'},{title:'方向',dataIndex:'side'},{title:'数量',dataIndex:'quantity'},{title:'原因',dataIndex:'reason'}]}/>{preview.diagnostics&&<Card className="mt-3"><b>风控诊断</b><pre className="text-xs">{JSON.stringify(preview.diagnostics,null,2)}</pre></Card>}</>:<Card>请先预览</Card>;
  const runsTab=<><Table rowKey="id" dataSource={runs} onRow={r=>({onClick:()=>void selectRun(r)})} columns={[{title:'日期',dataIndex:'tradeDate'},{title:'模式',dataIndex:'mode'},{title:'状态',dataIndex:'status'},{title:'订单数',dataIndex:'orderCount'}]}/>{selected&&<Card className="mt-3"><div className="flex justify-between"><b>运行详情 {selected.runUid}</b><Button size="small" onClick={()=>setSelected(null)}>关闭</Button></div><pre className="max-h-48 overflow-auto text-xs">{JSON.stringify(selected,null,2)}</pre><b>决策（{details.decisions.length}）</b><pre className="max-h-48 overflow-auto text-xs">{JSON.stringify(details.decisions,null,2)}</pre><b>订单（{details.orders.length}）</b><pre className="max-h-48 overflow-auto text-xs">{JSON.stringify(details.orders,null,2)}</pre></Card>}</>;
  return <><Card className="mb-3"><div className="flex justify-between"><b>数据同步状态（{sync?.tradeDate||'-'}）</b><Button size="small" onClick={()=>void refresh()}>刷新</Button></div><div className="mt-2 grid grid-cols-2">盘中：{syncItem(sync?.intraday)}　盘后：{syncItem(sync?.afterClose)}</div></Card><Tabs items={[{key:'config',label:'策略配置',children:configTab},{key:'preview',label:'调仓预览',children:previewTab},{key:'runs',label:'运行记录',children:runsTab},{key:'batches',label:'调仓批次',children:<Table rowKey="id" dataSource={batches} columns={[{title:'批次',dataIndex:'batchUid'},{title:'运行',dataIndex:'runId'},{title:'账户',dataIndex:'qmtAccount'},{title:'状态',dataIndex:'status'}]}/>}]} /> </>;
};
