import { useEffect, useState } from 'react';
import { Button, Card, Input, Select, Switch, Table, Tabs, Tag } from 'antd';
import { liveStrategyApi, type LiveStrategyConfig, type LiveStrategyDefinition, type LiveStrategyPreview } from '../../api/liveStrategy';

export const LiveStrategyPanel: React.FC = () => {
  const [config, setConfig] = useState<LiveStrategyConfig>({ strategyId: 'low-premium', strategyVersion: 'v1', qmtAccount: 'testS', enabled: false, symbols: [], parameters: {} });
  const [defs, setDefs] = useState<LiveStrategyDefinition[]>([]); const [preview, setPreview] = useState<LiveStrategyPreview | null>(null); const [runs, setRuns] = useState<any[]>([]); const [batches, setBatches] = useState<any[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { void Promise.all([liveStrategyApi.getConfig(), liveStrategyApi.listStrategies(), liveStrategyApi.listRuns(), liveStrategyApi.listBatches()]).then(([c, d, r, b]) => { if (c.qmtAccount) setConfig(c); setDefs(d); setRuns(r); setBatches(b); }).catch(() => undefined); }, []);
  const definition = defs.find((d) => d.strategyId === config.strategyId); const parameters = definition?.parameters || [];
  const action = async (fn: () => Promise<any>, success: string) => { setBusy(true); try { const result = await fn(); if (result?.rebalance) setPreview(result); setMessage(success); setRuns(await liveStrategyApi.listRuns()); setBatches(await liveStrategyApi.listBatches()); } finally { setBusy(false); } };
  const fields = parameters.map((p) => <label key={p.key} className="text-sm"><span>{p.label}</span><Input className="mt-1" type={p.type === 'integer' || p.type === 'number' ? 'number' : 'text'} value={String(config.parameters[p.key] ?? p.default ?? '')} onChange={(e) => setConfig({ ...config, parameters: { ...config.parameters, [p.key]: p.type === 'integer' ? Number.parseInt(e.target.value, 10) : p.type === 'number' ? Number(e.target.value) : e.target.value } })} /></label>);
  return <Tabs items={[{ key: 'config', label: '策略配置', children: <Card><div className="grid gap-3 sm:grid-cols-4"><label className="text-sm">QMT 账户<Select className="mt-1 w-full" value={config.qmtAccount} options={[{ value: 'testS', label: 'testS' }, { value: '135129739', label: '135129739' }]} onChange={(v) => setConfig({ ...config, qmtAccount: v })} /></label><label className="text-sm">策略<Select className="mt-1 w-full" value={config.strategyId} options={defs.map((d) => ({ value: d.strategyId, label: `${d.name} (${d.strategyId})` }))} onChange={(v) => { const d = defs.find((x) => x.strategyId === v); setConfig({ ...config, strategyId: v, parameters: Object.fromEntries((d?.parameters || []).map((p) => [p.key, p.default])) }); }} /></label><label className="flex items-center gap-2 text-sm pt-6">自动实盘<Switch checked={config.enabled} onChange={(v) => setConfig({ ...config, enabled: v })} /></label></div><p className="mt-2 text-xs text-secondary-text">{definition?.description}</p><div className="mt-3 grid gap-3 sm:grid-cols-4">{fields}</div><div className="mt-4 flex gap-2"><Button loading={busy} onClick={() => void action(() => liveStrategyApi.saveConfig(config), '配置已保存')}>保存配置</Button><Button loading={busy} onClick={() => void action(() => liveStrategyApi.preview(), '预览已生成')}>预览调仓</Button><Button type="primary" loading={busy} disabled={!config.enabled} onClick={() => void action(() => liveStrategyApi.run(), '实盘订单已生成')}>生成实盘订单</Button>{message && <Tag color="blue">{message}</Tag>}</div></Card>}, { key: 'preview', label: '调仓预览', children: preview ? <Table rowKey={(r) => `${r.side}-${r.symbol}`} dataSource={preview.rebalance} pagination={false} columns={[{ title: '标的', dataIndex: 'symbol' }, { title: '方向', dataIndex: 'side' }, { title: '数量', dataIndex: 'quantity' }, { title: '原因', dataIndex: 'reason' }]} /> : <Card>请先生成预览</Card>}, { key: 'runs', label: '运行记录', children: <Table rowKey="id" dataSource={runs} pagination={{ pageSize: 10 }} columns={[{ title: '日期', dataIndex: 'tradeDate' }, { title: '运行 UID', dataIndex: 'runUid' }, { title: '状态', dataIndex: 'status' }, { title: '调仓数', render: (_: unknown, r: any) => r.rebalance?.length || 0 }]} />}, { key: 'batches', label: '调仓批次', children: <Table rowKey="id" dataSource={batches} pagination={{ pageSize: 10 }} columns={[{ title: '批次 UID', dataIndex: 'batchUid' }, { title: '运行 ID', dataIndex: 'runId' }, { title: '账户', dataIndex: 'qmtAccount' }, { title: '状态', dataIndex: 'status' }, { title: '订单数', render: (_: unknown, r: any) => r.summary?.count || 0 }]} />}]} />;
};
